import types
import typing
import pandas as pd
from copy import deepcopy
import rotifer
logger = rotifer.logging.getLogger(__name__)

class SequenceCursor:
    def getids(self, obj):
        """
        Extract accessions from the objects generated by parser().

        Returns
        -------
        A set of strings.
        """
        import typing
        if isinstance(obj,list) or isinstance(obj,tuple):
            return set([ x.id for x in obj ])
        else:
            return {obj.id}

class IPGCursor:
    @property
    def columns(self):
        return self._columns + self._added_columns

    def getids(self,obj):
        if not isinstance(obj,list):
            obj = [obj]
        ids = set()
        for o in obj:
            ids.update(set(o.pid))
            ids.update(set(o.representative))
        return ids

class GenomeCursor:
    def getids(self,obj):
        if isinstance(obj,types.NoneType):
            return set()
        elif isinstance(obj,set):
            return deepcopy(obj)
        elif not isinstance(obj,list):
            obj = [obj]
        assemblies = set()
        for s in obj:
            if hasattr(s,"assembly"):
                if isinstance(s.assembly,str):
                    assemblies.add(s.assembly)
                else:
                    logger.warning(f'Unknown assembly type {type(assembly)}: {assembly}')
            elif hasattr(s,"dbxrefs") and isinstance(s.dbxrefs,list):
                for x in s.dbxrefs:
                    if 'Assembly:' in x:
                        assemblyID = x.split(':')[-1]
                        assemblies.add(assemblyID)
        return assemblies

    def fetcher(self, accession):
        tries = self.tries
        targets = self.parse_ids(accession)
        stream = []
        for acc in targets:
            fh = self.open_genome(acc)
            if fh == None:
                continue
            fh.assembly = acc
            stream.append(fh)
        self.tries = tries
        return stream

    def parser(self, stream, accession):
        from Bio import SeqIO
        stack = []
        for fh in stream:
            if isinstance(fh,types.NoneType):
                continue
            for s in SeqIO.parse(fh,"genbank"):
                setattr(s,"assembly",fh.assembly)
                stack.append(s)
            fh.close()
        return stack

class GenomeFeaturesCursor(GenomeCursor):
    def getids(self,obj):
        if isinstance(obj,types.NoneType):
            return set()
        elif isinstance(obj,set):
            return deepcopy(obj)
        elif isinstance(obj,list):
            return set([ x.assembly for x in obj ])
        elif isinstance(obj,pd.DataFrame) and "assembly" in obj.columns:
            return set(obj.assembly)
        else:
            raise TypeError(f'Unknown object type {type(obj)}: {obj}')

    def parser(self, stream, accession):
        from Bio import SeqIO
        from rotifer.genome.utils import seqrecords_to_dataframe
        if not isinstance(stream, list):
            stream = [stream]
        data = []
        for fh in stream:
            datum = SeqIO.parse(fh,"genbank")
            datum = seqrecords_to_dataframe(
                datum,
                exclude_type = self.exclude_type,
                autopid = self.autopid,
                assembly = fh.assembly,
                codontable = self.codontable,
            )
            data.append(datum)
            fh.close()
        if len(data) > 0:
            data = pd.concat(data)
        else:
            data = seqrecords_to_dataframe([])
        return data

    def fetchall(self, accessions, *args, **kwargs):
        """
        Fetch all accessions as a single dataframe.

        Parameters
        ----------
        accessions: list of strings
          Database accessions

        Returns
        -------
        Pandas dataframe or derived class.
        """
        from rotifer.genome.utils import seqrecords_to_dataframe
        stack = []
        for df in self.fetchone(accessions):
            stack.append(df)
        if stack:
            return pd.concat(stack, ignore_index=True)
        else:
            return seqrecords_to_dataframe([])

class GeneNeighborhoodCursor:
    def getids(self, obj, ipgs=None):
        import types

        # extract ids from dataframe
        if isinstance(obj,pd.DataFrame):
            # Load columns
            columns = self.column
            if not isinstance(columns,typing.Iterable) or isinstance(columns,str):
                columns = [columns]
            else:
                columns = list(columns)

            # when searching for proteins, ensure all columns with protein IDs are used
            pids = ['pid','replaced','representative']
            if set(columns).intersection(pids):
                columns += [ x for x in pids if x not in columns ]

            # Load identifiers from object
            ids = set()
            for col in columns:
                if col in obj.columns:
                    ids.update(set(obj[col].dropna().drop_duplicates()))

        # If obj is not a Pandas Dataframe
        elif not isinstance(obj,typing.Iterable) or isinstance(obj,str):
            ids = {obj}
        elif isinstance(obj,typing.Iterable):
            ids = set(obj)
        else:
            logger.error(f'Unknown type {type(obj)}')

        # Add synonyms from IPGs
        if not isinstance(ipgs,types.NoneType):
            ipgids = ipgs[ipgs.pid.isin(ids) | ipgs.representative.isin(ids)].id
            ipgids = ipgs[ipgs.id.isin(ipgids)]
            ids.update(ipgids.pid.dropna())
            ids.update(ipgids.representative.dropna())

        return ids

    def ipgs_to_dict(self, ipgs, column='assembly'):
        d = { k: v.set_index('pid').representative.to_dict() for k,v in ipgs.groupby(column) }
        return d

    def ipg_proteins(self, ipgs):
        allipgids = set(ipgs.pid).union(ipgs.representative.drop_duplicates())
        return allipgids

    def genome_ids(self, obj):
        if not isinstance(obj,list):
            obj = [obj]
        ids = set()
        for o in obj:
            ids.update(o[self._target_column].drop_duplicates().dropna())
        return ids

    def fetchall(self, accessions, ipgs=None):
        """
        Fetch all neighbors from nucleotide sequences.

        Parameters
        ----------
        accessions: list of strings
          NCBI protein identifiers

        Returns
        -------
        rotifer.genome.data.NeighborhoodDF
        """
        stack = []
        for df in self.fetchone(accessions, ipgs=ipgs):
            stack.append(df)
        if stack:
            return pd.concat(stack, ignore_index=True)
        else:
            return seqrecords_to_dataframe([])


class MappingCursor:
    """
    Mixin for cursors that translate identifiers through UniProt.

    Every such query has the same shape, whichever direction it runs
    in: identifiers of one or more databases are matched, their
    UniProtKB accessions are found, and the identifiers those
    accessions carry in one or more other databases are returned.
    Asking for the cross-references of an accession, asking which
    accession an external identifier belongs to, and translating
    between two external databases are that one query with different
    ends pinned, so cursors mixing this class in implement it once.

    The two ends are named by :meth:`fetchall` and :meth:`fetchone`
    rather than by the constructor, because they describe a question
    rather than a data source: one cursor can answer many of them.

    Attributes
    ----------
    columns : list of str
        ``['source', 'source_type', 'accession', 'target',
        'target_type']``: the queried identifier, the database it
        belongs to, the UniProtKB accession linking the two ends, the
        identifier found, and the database that one belongs to.
    """

    #: Name standing for a UniProtKB accession where a database name
    #: is expected. It is not a row of the mapping table but its join
    #: key, so both ends accept it and mean the accession itself.
    UNIPROTKB = 'UniProtKB-AC'

    _columns = ['source','source_type','accession','target','target_type']

    @property
    def columns(self):
        """
        Column names of the mapping dataframe.

        Returns
        -------
        list of str
        """
        return list(self._columns)

    @staticmethod
    def parse_databases(databases):
        """
        Normalize a ``source`` or ``target`` argument to a list.

        Parameters
        ----------
        databases : str, iterable of str or None
            One database name, several, or None for every database.

        Returns
        -------
        list of str or None
            None when no filter was asked for, which every backend
            reads as "any database".
        """
        if isinstance(databases, types.NoneType):
            return None
        if isinstance(databases, str) or not isinstance(databases, typing.Iterable):
            databases = [databases]
        names = [ str(x) for x in databases if not isinstance(x, types.NoneType) ]
        return names or None

    def databases(self):
        """
        Name the databases this cursor can map to and from.

        A backend that knows its own vocabulary lets a delegator ask
        it only for the databases it could answer for, and record the
        rest as unanswerable here rather than as absent everywhere.
        The distinction matters: a database missing from a backend is
        a gap in that copy of the data, while a database no backend
        supports is a gap in the answer.

        Returns
        -------
        set of str or None
            None when the cursor cannot enumerate them, which is read
            as "any", so nothing is narrowed on its account.
        """
        return None

    def unsupported(self, databases):
        """
        Pick the databases this cursor cannot answer for.

        Parameters
        ----------
        databases : list of str or None
            Databases asked for, or None for every database.

        Returns
        -------
        list of str
            Empty when the cursor supports them all, or cannot say.
        """
        known = self.databases()
        if isinstance(known, types.NoneType) or isinstance(databases, types.NoneType):
            return []
        return [ x for x in databases if x != self.UNIPROTKB and x not in known ]

    def supported(self, databases):
        """
        Narrow a list of databases to the ones this cursor can serve.

        Parameters
        ----------
        databases : list of str or None
            Databases asked for, or None for every database.

        Returns
        -------
        list of str or None
            None is passed through, meaning every database this
            cursor has.
        """
        known = self.databases()
        if isinstance(known, types.NoneType) or isinstance(databases, types.NoneType):
            return databases
        return [ x for x in databases if x == self.UNIPROTKB or x in known ]

    def empty(self):
        """
        Build an empty mapping dataframe.

        Returns
        -------
        pandas.DataFrame
            No rows, and the columns listed in :attr:`columns`.
        """
        return pd.DataFrame([], columns=self.columns)

    def getids(self, obj, *args, **kwargs):
        """
        Report which queried identifiers were translated.

        Only the ``source`` column is read. It holds what the caller
        asked about, so what a delegator still has to look for
        elsewhere is exactly what is missing from it; the identifiers
        found are answers, not queries, and counting them would mark
        the wrong things as done.

        Parameters
        ----------
        obj : pandas.DataFrame, set, str, iterable or None
            Mappings produced by the cursor, or a collection of
            identifiers, returned as a set.

        Returns
        -------
        set of str
        """
        if isinstance(obj, types.NoneType):
            return set()
        elif isinstance(obj, set):
            return deepcopy(obj)
        elif isinstance(obj, pd.DataFrame):
            if obj.empty or 'source' not in obj.columns:
                return set()
            return set(obj['source'].dropna().astype(str))
        elif isinstance(obj, str):
            return {obj}
        elif isinstance(obj, typing.Iterable):
            return set([ str(x) for x in obj ])
        else:
            raise TypeError(f'Unknown object type {type(obj)}: {obj}')

    def fetchall(self, accessions, source=None, target=None, *args, **kwargs):
        """
        Translate every identifier, as a single dataframe.

        Parameters
        ----------
        accessions : str or iterable of str
            Identifiers to translate.
        source : str or list of str, optional
            Databases the queried identifiers belong to. None accepts
            any, and :attr:`UNIPROTKB` means they are UniProtKB
            accessions.
        target : str or list of str, optional
            Databases to translate into. None returns every database,
            and :attr:`UNIPROTKB` returns the accession itself.

        Returns
        -------
        pandas.DataFrame
            The columns listed in :attr:`columns`. Empty, with those
            columns, when nothing is found.
        """
        stack = []
        for df in self.fetchone(accessions, source=source, target=target, *args, **kwargs):
            stack.append(df)
        if stack:
            return pd.concat(stack, ignore_index=True)
        else:
            return self.empty()
